#!/bin/bash

function DIR {
    echo "$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
}

# Remove previous hydra pid file so that we can wait for the new one.
rm hydra.pid
# Launch hydra in background.
bash $(DIR)/hydra hydra.pid &> hydra.log &
# Wait for pid file.
while [ ! -s hydra.pid  ]; do sleep 0.1; done
# Attach gdb to hydra. Sudo is needed because we are attached across a PID namespace.
sudo gdb $(DIR)/build/native-image/polyglot-proxy $(cat hydra.pid)
