#!/bin/bash

function DIR {
    echo "$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
}

# Note 1: unshare is necessary so that graalvisor lives in a different pid namespace (required for svm snapshotting).
# Note 2: setarch is necessary to disable ASRL, which is relevant for svm snapshotting (accessible through context-sandbox).
unshare --map-root-user --keep-caps --mount-proc --fork --pid \
setarch -R \
gdb -x graalvisor-gdb-commands.txt -ex "set environment LD_PRELOAD $(DIR)/src/main/c/svm-snapshot/deps/dlmalloc/hydralloc.so" \
$(DIR)/build/native-image/polyglot-proxy
