#!/bin/bash

if [ -z "${ARGO_HOME}" ]; then
    echo "ARGO_HOME is not defined. Existing..."
    exit 1
fi

pidfile=$1

function get_child_pid {
    ppid=$1
    attempts=10
    for ((i=0; i<attempts; i++))
    do
        cpid=$(pgrep -P $ppid)
        [[ ! -z $cpid ]] && break
        sleep .1
    done
    echo $cpid
}

# Uncomment to enable strace. The log will be put next to the graalvisor binary.
#trace_syscalls="strace -f -o $(dirname $graalvisor)/strace.log"

# This is important to ensure that we can load many (>100k) sandboxes.
# sudo sysctl -w vm.max_map_count=2000000

# Note 1: unshare is necessary so that graalvisor lives in a different pid namespace (required for svm snapshotting).
# Note 2: setarch is necessary to disable ASRL, which is relevant for svm snapshotting (accessible through context-sandbox).
# Note 3: for large heaps, add `-Xmx128g` next to graalvisor.
$trace_syscalls \
env LD_PRELOAD=$ARGO_HOME/graalvisor/src/main/c/svm-snapshot/deps/dlmalloc/hydralloc.so \
unshare --map-root-user --keep-caps --mount-proc --fork --pid \
setarch -R \
$ARGO_HOME/graalvisor/build/native-image/polyglot-proxy &

# The quest to find graalvisor's pid! Note that we want the pid as seen from the default namespace.
if [ ! -z "$pidfile" ]
then
    # PID of unshare (or strace).
    upid=$!
    # PID of graalvisor (or unshare).
    gpid=$(get_child_pid $upid)
    # If strace is being used, we need to go one level deeper.
    if [ ! -z "$trace_syscalls" ]
    then
        # PID of graalvisor.
        ggpid=$(get_child_pid $gpid)
        echo -n "$ggpid" > $pidfile
    else
        echo -n "$gpid" > $pidfile
    fi
fi

# Wait for graalvisor to terminate.
wait
