FROM debian AS argo-hotspot
ARG ENTRYPOINT_COMMAND
ENV ENTRYPOINT_COMMAND=${ENTRYPOINT_COMMAND}
COPY disk/ /
ENV JAVA_HOME=/jvm
ENTRYPOINT $ENTRYPOINT_COMMAND

FROM argo-hotspot AS argo-hotspot-agent
ENTRYPOINT $ENTRYPOINT_COMMAND
